config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, :only => [:index, :show, :destroy] do
    put 'set_role'
    put 'password_reset_instructions'
  end
  
  get 'home/index'
  get 'welcome', :controller => 'home', :action => :welcome
  get 'business/index'

  resources :default_settings, :only => [:index, :edit, :update]
  resources :default_settings_emails
  
  resources :businesses do
    resources :create, controller: 'businesses/create', :only => [:show, :create, :update]
    collection do
      get 'business_listing_map'
      get 'business_listing'
      get 'maps'
      get 'get_map_markers'
    end
    put 'approve_business'
    put 'pause_business'
  end
  match "/create_business_wizard" => "businesses#create_business_wizard", :via => [:get]

  resources :business_types do
    get 'business_subtype_options', :on => :collection
  end
  resources :business_subtypes, :only => [:new, :create, :edit, :update, :destroy]
  resources :service_types
  resources :zones do
    get 'zone_region_options', :on => :collection
  end
  resources :regions
  resources :contacts, :only => [:new, :create, :edit, :update, :destroy]
  resources :awards, :only => [:new, :create, :edit, :update, :destroy]

  root 'home#index'
  #root 'businesses#index'
end

app/models/business.rb
class Business < ApplicationRecord
  belongs_to :business_type, optional: true
  belongs_to :region, optional: true
  has_and_belongs_to_many :business_subtypes
  has_and_belongs_to_many :service_types
  has_and_belongs_to_many :zones
  has_many :contacts, :dependent => :destroy
  has_many :awards, :dependent => :destroy
  belongs_to :owner, class_name: :User, foreign_key: :owner_id, optional: true

  has_attached_file :logo, 
    styles: { 
        :large => ["520x180>",:jpg],
        :medium => ["260x90>",:jpg],
        :thumb => ["130x45>",:jpg]
    },
    :convert_options => {
        :thumb => "-quality 75 -strip" },
    :url => "/uploads/db_images/:id/:style_:basename.:extension",  
    :path => ":rails_root/public/uploads/db_images/:id/:style_:basename.:extension",
    :default_url => '/images/no-image.jpg'

  validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  validates :name, presence: true, if: :active_or_info?
  validates :address1, :city, :state, :zipcode, :phonenum, :email, presence: true, if: :active_or_location?
  validates :business_type_id, presence: { message: "must select at least one" }, if: :active_or_services?
  validates :service_types, presence: { message: "must select at least one" }, if: :active_or_services?
  validates :zones, presence: { message: "must select at least one" }, if: :active_or_services?
  validates :region, presence: { message: "must select one when zone has regions" }, if: -> record { active_or_services? && zone_has_regions? }
  #validates :business_type_id, presence: true, if: :active_or_extras?
  #validates :business_type_id, presence: true, if: :active_or_contacts?

  def active?
    status == 'active'
  end

  def active_or_info?
    status.include?('business_info') || active?
  end

  def active_or_location?
    status.include?('business_location') || active?
  end

  def active_or_services?
    status.include?('business_services') || active?
  end

  def active_or_extras?
    status.include?('business_extras') || active?
  end

  def active_or_contacts?
    status.include?('business_contacts') || active?
  end
  
  def zone_has_regions?
    self.zones.present? && (self.zones.first.regions.size > 0)
  end
end

app/models/business_type.rb
class BusinessType < ApplicationRecord
    has_many :businesses
    has_many :business_subtypes, :dependent => :destroy
    
    validates :name, uniqueness: true
    validates :name, presence: true
    validates :title_for_subtypes, presence: true
end

app/controllers/businesses/create_controller.rb
class Businesses::CreateController < ApplicationController
  include Wicked::Wizard
  before_action :set_progress, only: [:show]

  steps :business_info, :business_location, :business_services, :business_extras, :business_contacts

  def show
    @business_types = BusinessType.all.order("name")
    @business_subtypes = BusinessType.first.business_subtypes
    @service_types = ServiceType.all.order("name")
    @zones = Zone.all.order("name")
    @business_regions = Zone.all.order("name")
    @users = User.all.order("email")

    @business = Business.find(params[:business_id])
    render_wizard
  end

  def update
    @business_types = BusinessType.all.order("name")
    @business_subtypes = BusinessType.first.business_subtypes
    @service_types = ServiceType.all.order("name")
    @zones = Zone.all.order("name")
    @business_regions = Zone.all.order("name")
    @users = User.all.order("email")

    @business = Business.find(params[:business_id])
    @business.website = sanitize_website(@business.website) unless @business.website.nil?
    @business.status = (step == steps.last ? 'active' : step.to_s)
    if step.to_s == "business_services"
      if params[:business][:region_id].nil? # if no region was selected, clear the current business region_id
        @business.region_id = nil
      end
    end
    @business.update(business_params)
    render_wizard @business
  end
  
  def create
    @business = Business.create
    @business.save
    redirect_to wizard_path(steps.first, business_id: @business.id)
  end

  private
  def business_params
    params.require(:business).permit(:name,:logo,:business_type_id,{:business_subtype_ids=>[]},{:service_type_ids=>[]},:zone_ids,:region_id,:hours,
    :website,:address1,:address2,:city,:state,:zipcode,:phonenum,:email,:notes,:yelp_url,:business_listing_zone,:happy_hour,:food_truck,:award_id,:owner_id,
    :status, :approved )
  end
  
  def finish_wizard_path
    businesses_path
  end

  def set_progress
    if wizard_steps.any? && wizard_steps.index(step).present?
      @progress = ((wizard_steps.index(step) + 1).to_d / wizard_steps.count.to_d) * 100
    else
      @progress = 0
    end
  end

  def sanitize_website(url)
    unless url.include?("http://") || url.include?("https://")
      url = "http://" + url
    end
    return url
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  load_and_authorize_resource :except => [:maps, :business_listing, :business_listing_map]

  skip_before_action :authenticate_user!, :only => [:maps, :business_listing, :business_listing_map]
  layout :determine_layout
  helper_method :sort_column, :sort_direction

  def index
    if can? :manage, Business
      @businesses = Business.left_outer_joins(:business_type)
      @businesses = @businesses.where('businesses.name LIKE ?', "%#{params[:search_query]}%") if params[:search_query].present?
      @businesses = @businesses.where(status: params[:status_select]) if params[:status_select].present?
    else
      @businesses = Business.where(:owner_id => current_user).left_outer_joins(:business_type)
    end
    @businesses = @businesses.where.not(name: [nil, ""])
    if !params[:type].nil?
      @businesses = @businesses.where('business_types.name = ?', params[:type])
    end
    if current_user.admin_role? and !params[:owner].nil?
      @businesses = @businesses.where('businesses.owner_id = ?', params[:owner])
    end
    @businesses = @businesses.order(sort_column + " " + sort_direction).distinct
  end
  
  def show
    @business = Business.find(params[:id])
    @business_subtypes = @business.business_subtypes
  end

  def new
    @business_types = BusinessType.all.order("name")
    @business_subtypes = BusinessType.first.business_subtypes
    @service_types = ServiceType.all.order("name")
    @zones = Zone.all.order("name")
    @business_regions = Zone.first.regions
    @users = User.all.order("email")

    @business = Business.new
    @business.owner_id = current_user.id
  end

  def create_business_wizard
    # Find businesses of current user that are not active
    @businesses = Business.where(:owner_id => current_user.id)
    @businesses = @businesses.where.not(status: "active").where.not(status: "approved")
    if @businesses.empty?
      @business = Business.new({owner_id: current_user.id})
      @business.status = 'new'
      @business.save!
      puts "*** create new ****"+@business.inspect
      redirect_to business_create_path(business_id: @business.id, id: :business_info)
    else
      @business = @businesses.first
      @business.status = 'business_info' if @business.status == 'new'
      puts "*** found existing ****"+@business.inspect
      redirect_to business_create_path(business_id: @business.id, id: @business.status)
    end
  end

  def create
    if params[:cancel_button]
      redirect_to businesses_path
    else
      @business_types = BusinessType.all.order("name")
      @service_types = ServiceType.all.order("name")
      @zones = Zone.all.order("name")

      @business = Business.new(business_params)
      @business.owner_id = current_user.id
      @business.status = "approved"
      if @business.save
        flash[:notice] = "Business Created"
        redirect_to @business
      else
        flash[:notice] = "Business Creation Failed"
        render :action => :new
      end
    end    
  end

  def edit
    @business_types = BusinessType.all.order("name")
    if @business.business_type.nil?
      @business_subtypes = BusinessType.first.business_subtypes
    else
      @business_subtypes = @business.business_type.business_subtypes
    end
    @service_types = ServiceType.all.order("name")
    @zones = Zone.all.order("name")
    if @business.zones.nil?
      @business_regions = Zone.first.regions
    else
      @business_regions = Region.where(:zone_id => @business.zones ).order(:name)
    end
    @users = User.all.order("email")

    @business = Business.find(params[:id])
  end

  def update
    if params[:cancel_button]
      redirect_to @business
    else
      @business_types = BusinessType.all.order("name")
      if @business.business_type.nil?
        @business_subtypes = BusinessType.first.business_subtypes
      else
        @business_subtypes = @business.business_type.business_subtypes
      end
      @service_types = ServiceType.all.order("name")
      @zones = Zone.all.order("name")
      if @business.zones.nil?
        @business_regions = Zone.first.regions
      else
        @business_regions = Region.where(:zone_id => @business.zones ).order(:name)
      end

      @business = Business.find(params[:id])
      if !current_user.admin_role?    # current user is not an Admin so require the business to be Approved
        @business.status = "active"
        @business.approved = false
      end
      if params[:business][:region_id].nil? # if no region was selected, clear the current business region_id
        @business.region_id = nil
      end
      if @business.update(business_params)
          flash[:notice] = "Business Updated"
          if current_user = @business.owner   # If owner makes a change, email changes
            @default_settings_email = DefaultSettingsEmail.find_by(name: 'Business Updated')
            BusinessMailer.business_updated(@business,@default_settings_email).deliver_later unless @default_settings_email.nil? 
          end
          @default_settings_email = DefaultSettingsEmail.find_by(name: 'Business Waiting For Approval')
          BusinessMailer.business_waiting_for_approval(@business,@default_settings_email).deliver_later unless @default_settings_email.nil? 
          redirect_to @business
      else
          flash[:notice] = "Business Update Failed"
          render :action => :edit
      end
    end
  end

  def destroy
    @business = Business.find(params[:id])
    if @business.destroy
        flash[:notice] = "Business Deleted"
        redirect_to businesses_path
    else
        flash[:notice] = "Business Deletion Failed"
        redirect_to businesses_path
    end
  end
  
  def approve_business
    @business = Business.find(params[:business_id])
    if @business.present?
      @business.approved = true
      @business.status = "approved"
      if @business.save
        flash[:notice] = "Business Approved"
        redirect_to @business
      else
        flash[:notice] = "Business Approval Failed"
        redirect_to @business
      end
    end
  end

  def pause_business
    @business = Business.find(params[:business_id])
    if @business.present?
      if @business.pause_listing
        @business.pause_listing = false
        if @business.save
          flash[:notice] = "Business Unpaused"
          redirect_to @business
        else
          flash[:notice] = "Unpause Failed"
          redirect_to @business
        end
      else
        @business.pause_listing = true
        if @business.save
          flash[:notice] = "Business Paused"
          redirect_to @business
        else
          flash[:notice] = "Pause Failed"
          redirect_to @business
        end
      end
    end
  end
  
  def business_listing_map
    @business_types = BusinessType.order("name")
    @business_type_label = BusinessType.where('business_types.name = ?', params[:type]).first
    if params[:type].nil?
      # switch to filtering by type when no type param
      # @business_subtypes = BusinessSubtype.all.joins(:business_type).order("business_types.name","business_subtypes.name")
    else
      @business_subtypes = BusinessSubtype.joins(:business_type).where('business_types.name = ?', params[:type]).order("name") unless params[:type].nil?
    end
    @service_types = ServiceType.all.order("name")

    # lists businesses for embedding into an external webpage using paramters 'type', 'service_type', 'zone'
    @businesses = Business.all
    @businesses = @businesses.left_outer_joins(:business_type).where('business_types.name = ?', params[:type]) unless params[:type].nil? || params[:type].empty?
    @businesses = @businesses.left_outer_joins(:business_subtypes).where('business_subtypes.name = ?', params[:business_subtype]) unless params[:business_subtype].nil? || params[:business_subtype].empty?
    @businesses = @businesses.left_outer_joins(:zones).where('zones.name = ?', params[:zone]) unless params[:zone].nil? || params[:zone].empty?
    @businesses = @businesses.left_outer_joins(:service_types).where('service_types.name = ?', params[:service_type]) unless params[:service_type].nil? || params[:service_type].empty?
    @businesses = @businesses.where(happy_hour: true) unless params[:happy_hour] != 'true'
    @businesses = @businesses.where(food_truck: true) unless params[:food_truck] != 'true'
    @businesses = @businesses.where(approved: true).where('pause_listing is null or pause_listing != true').distinct
    @businesses = @businesses.order('city').order('name')

    @business_locations = get_business_locations(@businesses).reject(&:blank?)
    params[:zoom] = (params[:zoom] && params[:zoom].to_i > 0) ? params[:zoom] : 11
    params[:center] = get_center_geocode(params[:center],params[:zone])
  end

  def business_listing
    @business_types = BusinessType.order("name")
    @business_type_label = BusinessType.where('business_types.name = ?', params[:type]).first
    if params[:type].nil?
      # switch to filtering by type when no type param
      # @business_subtypes = BusinessSubtype.all.joins(:business_type).order("business_types.name","business_subtypes.name")
    else
      @business_subtypes = BusinessSubtype.joins(:business_type).where('business_types.name = ?', params[:type]).order("name") unless params[:type].nil?
    end
    @service_types = ServiceType.all.order("name")

    # lists businesses for embedding into an external webpage using paramters 'type', 'service_type', 'zone'
    @businesses = Business.all
    @businesses = @businesses.left_outer_joins(:business_type).where('business_types.name = ?', params[:type]) unless params[:type].nil? || params[:type].empty?
    @businesses = @businesses.left_outer_joins(:business_subtypes).where('business_subtypes.name = ?', params[:business_subtype]) unless params[:business_subtype].nil? || params[:business_subtype].empty?

app/helpers/business/create_helper.rb
module Business::CreateHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper

  def business_address(business)
    address = ""
    address << business.address1 + ", " unless business.address1.nil?
    address << business.address2 + " " unless business.address2.nil?
    return address
  end

  def business_address_city(business)
    address = ""
    address << business.address1 + ", " unless business.address1.nil?
    address << business.address2 + " " unless business.address2.nil?
    address << business.city unless business.city.nil?
    return address
  end

  def business_address_city_state(business)
    address = ""
    address << business.address1 + ", " unless business.address1.nil?
    address << business.address2 + " " unless business.address2.nil?
    address << business.city + " " unless business.city.nil?
    address << business.state unless business.state.nil?
    return address
  end

  def business_address_city_state_zip(business)
    address = ""
    address << business.address1 + ", " unless business.address1.nil?
    address << business.address2 + " " unless business.address2.nil?
    address << business.city + " " unless business.city.nil?
    address << business.state + " " unless business.state.nil?
    address << business.zipcode unless business.zipcode.nil?
    return address
  end

  def shrink_url_field(url)
    unless url.nil?
      url = url.split('/')[2]
      url = url.gsub('www.','') unless url.nil?
      url = url.gsub('https://','') unless url.nil?
      url = url.gsub('http://','') unless url.nil?
    end
  end
end

app/views/businesses/_table_row.html.erb
<tr>
	<td class="text-center " style="width:150px;">
		<% case table_row.status 
	     when "approved" %>
			<% if table_row.pause_listing %>
				<i class="fa fa-pause" data-toggle="tooltip"  title="Listing Paused" style="color: red;font-size: 1.5rem;"></i>
			<% else %>
				<i class="fa fa-circle" data-toggle="tooltip"  title="Approved" style="color: green;font-size: 1.5rem;"></i>
			<% end %>
	  <% when "active" %><i class="fa fa-clock-o" data-toggle="tooltip"  title="Waiting for approval" style="font-size: 1.5rem;"></i>
		<% else %><i class="fa fa-exclamation-triangle" data-toggle="tooltip"  title="Business creation needs completion" style="color: red;font-size: 1.5rem;"></i>
	  <% end %>
	</td>
	<td class="text-center d-none d-sm-table-cell"><%= image_tag table_row.logo.url(:thumb) unless table_row.logo_file_name.nil? %></td>	
	<td>
		<% if (can? :manage, Business) || (["approved","active"].include? table_row.status) %>
			 <%= link_to table_row.name, business_path(table_row)  %>
		<% else %>
			 <%= link_to table_row.name, create_business_wizard_path  %>
	  <% end %>
	</td>
	<td class="text-center d-none d-sm-table-cell">
		- <%= table_row.business_type.name unless table_row.business_type.nil? %> -<br/>
		<% table_row.business_subtypes.each do |subtype| %>
			<%= subtype.name %><br/>
		<% end %>
	</td>
	<td class="d-none d-lg-table-cell"><%= business_address_city(table_row) %></td>
	<td class="text-center d-none d-lg-table-cell"><%= table_row.updated_at.strftime('%m/%d/%y %I:%M%p') unless table_row.updated_at.nil? %>	</td>

	<td class="text-center">
		<div class="btn">
			<% if (can? :manage, Business) || (["approved","active"].include? table_row.status) %>
				<%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_business_path(table_row),
					title: 'Edit', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
			<% end %>
			<%= link_to icon('trash-o fa-lg'), 
				business_path(table_row),
				:method=> :delete, :action => 'destroy',
				data: {
					title: 'Delete '+table_row.name+'?', 
					confirm:'Delete this business from the system?'},
				title: 'Delete', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
		</div>
	</td>
</tr>

app/views/businesses/show.html.erb
<div class="business_heading">
	<h1>
		<%= image_tag @business.logo.url(:medium) %>
		<%= @business.name %>
		<div class="float-right"><%= link_to "All Businesses", businesses_path, :class => 'btn btn-primary' %></div>
		<div class="float-right"><%= link_to "Edit", edit_business_path(@business), :class => 'btn btn-primary' %></div>
	</h1>
</div>

<div class="business_block" >
	<hr/>
	<div class="form-group row">
		<label for="status" class="col-1"><h5>Status:</h5></label>
		<div class="col-3">
			<% case @business.status 
		     when "approved" %> <i class="fa fa-circle" style="color: green;"></i>&nbsp;&nbsp;Approved
		  <% when "active" %>
				<i class="fa fa-clock-o"></i>&nbsp;&nbsp;Waiting for approval
				<% if can? :manage, Business %>
					&nbsp;&nbsp;
					<%= link_to "Approve", business_approve_business_path(@business),
						:method=> :put, :action => 'approve_business', :class => 'btn btn-success',
						data: {
							title: 'Approve '+@business.name+'?', 
							confirm:'Proceeding will approve this business listing and publish online', 
							commit: 'Approve', 'commit-class': 'btn-success'},
						title: 'Approve', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
				<% end %>
			<% else %><i class="fa fa-exclamation-triangle" style="color: red;"></i>&nbsp;&nbsp;Business creation needs completion
		  <% end %>
		</div>
		<div class="col-3">
			<% if @business.status == "approved" %>
				<% if @business.pause_listing %>
					<%= link_to business_pause_business_path(@business),
						:method=> :put, :action => 'pause_business', :class => 'btn btn-danger',
						data: {
							title: 'Unpause?', 
							confirm:'Proceeding will unpause this business listing and allow it to publish online', 
							commit: 'Unpause', 'commit-class': 'btn-danger'},
						title: 'Unpause business listing', 'data-toggle' => 'tooltip', 'data-placement' => 'right' do %>
						<i class="fa fa-pause" aria-hidden="true"></i> Paused
					<% end %>
				<% else %>
					<%= link_to "Live", business_pause_business_path(@business),
						:method=> :put, :action => 'pause_business', :class => 'btn btn-success',
						data: {
							title: 'Pause '+@business.name+'?', 
							confirm:'Proceeding will pause this business listing and remove it from online', 
							commit: 'Pause', 'commit-class': 'btn-success'},
						title: 'Business listing is Live. Click to pause and take offline.', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
				<% end %>
			<% end %>
		</div>
		<div class="col-4">
			Last updated: <%= @business.updated_at.strftime('%m/%d/%Y %l:%M%P') %>
		</div> 
	</div>
	<hr/>

	<h5>Business Info:</h5>
	<div class="form-group row">
		<label for="name" class="offset-1 col-2">Name:</label>
		<%= render 'shared/field_missing_data', field: @business.name, required: true %>
		<div class="col-4">
			<h5><%= @business.name %></h5>
		</div>
		<% if (can? :manage, Business) %>
			<label for="name" class="offset-1 col-1">Owner:</label>
			<div class="col-3">
				<%= @business.owner.nil? ? "NA" : @business.owner.email%>
			</div>
		<% end %>
	</div>

	<div class="form-group row">
		<label for="business_type" class="offset-1 col-2">Type:</label>
		<%= render 'shared/field_missing_data', field: @business.business_type, required: true %>
		<div class="col-2">
			<%= @business.business_type.name unless @business.business_type.nil? %>
		</div>
		<label for="business_subtype" class="offset-1 col-2">
			<%= @business.business_type.name unless @business.business_type.nil? %> <%= @business.business_type.title_for_subtypes unless @business.business_type.nil? %>:
		</label>
		<%= render 'shared/field_missing_data', field: @business.business_subtypes, required: false %>
		<div class="col-3">
			<%= @business.business_subtypes.map{|v| v.name }.join(", ") %>
		</div>
	</div>

	<div class="form-group row">
		<label for="service_type" class="offset-1 col-2">Service Options:</label>
		<%= render 'shared/field_missing_data', field: @business.service_types, required: true %>
		<div class="col-3">
			<%= @business.service_types.map{|v| v.name }.join(", ") %>
		</div>
	</div>

	<div class="form-group row">
		<label for="hours" class="offset-1 col-2">Business Hours:</label>
		<%= render 'shared/field_missing_data', field: @business.hours, required: false %>
		<div class="col-6">
			<%= @business.hours %>
		</div>
	</div>
	<div class="form-group row">
		<label for="zones" class="offset-1 col-2">Business Zone:</label>
		<%= render 'shared/field_missing_data', field: @business.zones, required: true %>
		<div class="col-2">
			<%= @business.zones.map{|v| v.name }.join(", ") %>
		</div>
		<label for="region" class="offset-1 col-2">Region:</label>
		<div class="col-3">
			<%= @business.region.name unless @business.region.nil? %>
		</div>
	</div>
	<div class="form-group row">
		<div class="offset-2 col-1">
			<% if @business.happy_hour %>
				<i class="fa fa-check-square fa-2x"></i>
			<% else %>
				<i class="fa fa-ban fa-2x"></i>
			<% end %>
		</div>
		<label for="happy_hour" class="col-2">Happy Hour</label>
	</div>
	<div class="form-group row">
		<div class="offset-2 col-1">
			<% if @business.food_truck %>
				<i class="fa fa-check-square fa-2x"></i>
			<% else %>
				<i class="fa fa-ban fa-2x"></i>
			<% end %>
		</div>
		<label for="food_truck" class=" col-2">Food Truck</label>
	</div>
	<hr/>

	<div class="form-group row">
		<label for="address" class="offset-1 col-2">Address:</label>
		<%= render 'shared/field_missing_data', field: @business.address1, required: true %>
		<%= render 'shared/field_missing_data', field: @business.city, required: true %>
		<%= render 'shared/field_missing_data', field: @business.state, required: true %>
		<%= render 'shared/field_missing_data', field: @business.zipcode, required: true %>
		<div class="col-8">
			<%= business_address_city_state_zip(@business) %>
		</div>
	</div>

	<div class="form-group row">
		<label for="phonenum" class="offset-1 col-2">Phone Number:</label>
		<%= render 'shared/field_missing_data', field: @business.phonenum, required: true %>
		<div class="col-8">
			<%= number_to_phone(@business.phonenum) %>
		</div>
	</div>

	<div class="form-group row">
		<label for="email" class="offset-1 col-2">Email:</label>
		<%= render 'shared/field_missing_data', field: @business.email, required: true %>
		<div class="col-8">
			<%= @business.email %>
		</div>
	</div>

	<div class="form-group row">
		<label for="website" class="offset-1 col-2	">Website:</label>
		<%= render 'shared/field_missing_data', field: @business.website, required: false %>
		<div class="col-8">
			<%= @business.website %>
		</div>
	</div>

	<div class="form-group row">
		<label for="notes" class="offset-1 col-2">Yelp URL:</label>
		<div class="col-8">
			<%= @business.yelp_url %>
		</div>
	</div>
	<hr/>

	<div class="form-group row">
		<label for="notes" class="offset-1 col-2">Notes:</label>
		<div class="col-8">
			<%= @business.notes %>
		</div>
	</div>
	<hr/>

	<h5>Business Awards: <small><em>(<%= link_to 'add new award', new_award_path(:current_business=>@business) %>)</em></small></h5>
	<div class="offset-1 mw-100">
		<table class="table table-hover table-sm w-auto">
			<tbody>
				<% @business.awards.each do |award| %>
					<tr>
						<td><%= award.year %></td>
						<td><%= award.place %></td>
						<td><%= award.name %></td>
						<td><%= award.description %></td>
						<td class="text-center">
							<%= link_to icon('edit fa-lg'),
								edit_award_path(award,:current_business=>@business),
								title: 'Edit', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
						</td>
						<td class="text-center">
							<%= link_to icon('remove fa-lg'), 
								award_path(award), :class => "",
								:method=> :delete, :action => 'destroy',
								data: {
									title: 'Delete '+award.name+'?', 
									confirm:'Remove this award from the business?'},
								title: 'Delete', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<hr/>
	
	<h5>Business Contacts: <small><em>(<%= link_to 'add new contact', new_contact_path(:current_business=>@business) %>)</em></small></h5>
	<div class="offset-1 mw-100">
		<table class="table table-hover table-sm w-auto">
			<tbody>
				<% @business.contacts.each do |contact| %>
					<tr>
						<td><%= contact.name %></td>
						<td><%= number_to_phone(contact.phonenum) %></td>
						<td><%= contact.email %></td>
						<td class="text-center">
							<%= link_to icon('edit fa-lg'),
								edit_contact_path(contact,:current_business=>@business),
								title: 'Edit', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
						</td>
						<td class="text-center">
							<%= link_to icon('remove fa-lg'), 
								contact_path(contact), :class => "",
								:method=> :delete, :action => 'destroy',
								data: {
									title: 'Delete '+contact.name+'?', 
									confirm:'Remove this contact from the business?'},
								title: 'Delete', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>