config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, :only => [:index, :show, :destroy] do
    put 'set_role'
    put 'password_reset_instructions'
  end
  
  get 'home/index'
  get 'welcome', :controller => 'home', :action => :welcome
  get 'business/index'

  resources :default_settings, :only => [:index, :edit, :update]
  resources :default_settings_emails
  
  resources :businesses do
    resources :create, controller: 'businesses/create', :only => [:show, :create, :update]
    collection do
      get 'business_listing_map'
      get 'business_listing'
      get 'maps'
      get 'get_map_markers'
    end
    put 'approve_business'
    put 'pause_business'
  end
  match "/create_business_wizard" => "businesses#create_business_wizard", :via => [:get]

  resources :business_types do
    get 'business_subtype_options', :on => :collection
  end
  resources :business_subtypes, :only => [:new, :create, :edit, :update, :destroy]
  resources :service_types
  resources :zones do
    get 'zone_region_options', :on => :collection
  end
  resources :regions
  resources :contacts, :only => [:new, :create, :edit, :update, :destroy]
  resources :awards, :only => [:new, :create, :edit, :update, :destroy]

  root 'home#index'
  #root 'businesses#index'
end

app/controllers/service_types_controller.rb
class ServiceTypesController < ApplicationController
  load_and_authorize_resource

  def index
    @service_types = ServiceType.all.order('name')
  end

  def show
    @service_type = ServiceType.find(params[:id])
  end

  def new
    @service_type = ServiceType.new
  end

  def create
    if params[:cancel_button]
      redirect_to service_types_path
    else
      @service_type = ServiceType.new(service_type_params)
      if @service_type.save
        flash[:notice] = "Service Type Created"
        redirect_to service_types_path
      else
        flash[:error] = "Service Type Creation Failed"
        render :action => :new
      end
    end    
  end

  def edit
    @service_type = ServiceType.find(params[:id])
  end

  def update
    @service_type = ServiceType.find(params[:id])
    if @service_type.update_attributes(service_type_params)
        flash[:notice] = "Service Type Updated"
        redirect_to service_types_path
    else
        flash[:error] = "Service Type Update Failed"
        render :action => :edit
    end
  end

  def destroy
    @service_type = ServiceType.find(params[:id])
    if @service_type.destroy
        flash[:notice] = "Service Type Killed"
        redirect_to service_types_path
    else
        flash[:error] = "Service Type Deletion Failed"
        redirect_to service_types_path
    end
  end

  private
    def service_type_params
      params.require(:service_type).permit(:name)
    end
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/views/service_types/_table_row.html.erb
<tr>
	<td><%= table_row.name %></td>	

	<td class="text-center">
		<div class="btn">
			<%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_service_type_path(table_row),
				title: 'Edit', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
			<%= link_to icon('trash-o fa-lg'), 
				service_type_path(table_row),
				:method=> :delete, :action => 'destroy',
				data: {
					title: 'Delete '+table_row.name+'?', 
					confirm:'Delete this service type from the system?'},
				title: 'Delete', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
		</div>
	</td>
</tr>

app/views/service_types/edit.html.erb
<div class="service_type_heading">
	<h1><%= @service_type.name %></h1>
</div>

<div class="service_type_block" >
	<%= form_for(@service_type) do |f| %>
		<div class="form-group row">
			<label for="name" class="offset-1 col-3 col-form-label">Service Type:</label>
			<%= render 'shared/field_error_messages', object: @service_type, field: :name %>
			<div class="col-3">
				<%= f.text_field :name, class: "form-control" %>
			</div>
		</div>

		<div class="form-group row d-flex justify-content-end">
			<%= f.submit "Update", :class => 'btn btn-primary'%>
			<%= f.submit "Cancel", :name => 'cancel_button', :class => 'btn btn-primary'%>
		</div>
	<% end %>
</div>

app/views/service_types/index.html.erb
<div class="page-content">
	<div class="business_type_heading">
		<div class="d-flex justify-content-between align-items-center">
			<h2>Service Types</h2>
			<div class="float-right"><%= link_to "New Service Type", new_service_type_path %></div>
		</div>
	</div>

	<div class="service_type_block">
		<div class="">
			<% if @service_types %>
				<% unless @service_types.nil? %>
					<table id="services_types" class="table table-hover table-condensed table-striped table-sm">
						<thead class="">
							<tr>
								<th class="">Name</th>
								<th class="text-center">Action</th>
							</tr>
						</thead>
						<tbody>
							<%= render :partial => 'table_row', :collection => @service_types %>
						</tbody>
					</table>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/service_types/new.html.erb
<div class="service_type_heading">
	<h1><%= @service_type.name %></h1>
</div>

<div class="service_type_block" >
	<%= form_for(@service_type) do |f| %>
		<div class="form-group row">
			<label for="name" class="offset-1 col-3 col-form-label">Service Type:</label>
			<%= render 'shared/field_error_messages', object: @service_type, field: :name %>
			<div class="col-3">
				<%= f.text_field :name, class: "form-control" %>
			</div>
		</div>

		<div class="form-group row d-flex justify-content-end">
			<%= f.submit "Add", :class => 'btn btn-primary'%>
			<%= f.submit "Cancel", :name => 'cancel_button', :class => 'btn btn-primary'%>
		</div>
	<% end %>
</div>