config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, :only => [:index, :show, :destroy] do
    put 'set_role'
    put 'password_reset_instructions'
  end
  
  get 'home/index'
  get 'welcome', :controller => 'home', :action => :welcome
  get 'business/index'

  resources :default_settings, :only => [:index, :edit, :update]
  resources :default_settings_emails
  
  resources :businesses do
    resources :create, controller: 'businesses/create', :only => [:show, :create, :update]
    collection do
      get 'business_listing_map'
      get 'business_listing'
      get 'maps'
      get 'get_map_markers'
    end
    put 'approve_business'
    put 'pause_business'
  end
  match "/create_business_wizard" => "businesses#create_business_wizard", :via => [:get]

  resources :business_types do
    get 'business_subtype_options', :on => :collection
  end
  resources :business_subtypes, :only => [:new, :create, :edit, :update, :destroy]
  resources :service_types
  resources :zones do
    get 'zone_region_options', :on => :collection
  end
  resources :regions
  resources :contacts, :only => [:new, :create, :edit, :update, :destroy]
  resources :awards, :only => [:new, :create, :edit, :update, :destroy]

  root 'home#index'
  #root 'businesses#index'
end

app/views/shared/_create_business_progress.html.erb
<div class="col-md-12 progress_block">
	<div class="d-flex justify-content-center text-center">
		<% if past_step?(:business_info) || step.to_s == "business_info" %>
		  <div class="col">
				<%= link_to "Name", wizard_path(:business_info) %>
			</div>
		<% else %>
		  <div class="col">
				<div>Name</div>
			</div>
		<% end %>
		<% if past_step?(:business_location) || step.to_s == "business_location" %>
		  <div class="col">
				<%= link_to "Location", wizard_path(:business_location) %>
			</div>
		<% else %>
		  <div class="col">
				<div>Location</div>
			</div>
		<% end %>
		<% if past_step?(:business_services) || step.to_s == "business_services" %>
		  <div class="col">
				<%= link_to "Services", wizard_path(:business_services) %>
			</div>
		<% else %>
		  <div class="col">
				<div>Services</div>
			</div>
		<% end %>
		<% if past_step?(:business_extras) || step.to_s == "business_extras" %>
		  <div class="col">
				<%= link_to "Extras", wizard_path(:business_extras) %>
			</div>
		<% else %>
		  <div class="col">
				<div>Extras</div>
			</div>
		<% end %>
		<% if past_step?(:business_contacts) || step.to_s == "business_contacts" %>
		  <div class="col">
				<%= link_to "Contacts", wizard_path(:business_contacts) %>
			</div>
		<% else %>
		  <div class="col">
				<div>Contacts</div>
			</div>
		<% end %>
	</div>
	<div class="progress" style="height: 20px;" >
    <div class="dot-one info-color"></div>
		<div class="dot-two no-color"></div>
		<div class="dot-three no-color"></div>
		<div class="dot-four no-color"></div>
		<div class="dot-five no-color"></div>
    <div class="progress-bar info-color" role="progressbar" aria-valuenow="<%= @progress %>" aria-valuemax="100" style="width: <%= @progress %>%" >
    	
    </div>
  </div>
</div>

app/views/shared/_field_error_messages.html.erb
<div class="field_error_messages">
	<% object.errors[field].each do |error| %>
		<div>* <%= error %></div>
	<% end %>
</div>

app/views/shared/_field_missing_data.html.erb
<% if field.kind_of? String %>
	<% if field.nil? %>
		<% if required %>
			<div class="field_error_messages">
				* required info
			</div>
		<% else %>
			<div class="field_error_messages">
			</div>
		<% end %>
	<% end %>
<% else %>
	<% if field.blank? %>
		<% if required %>
			<div class="field_error_messages">
				* required info
			</div>
		<% else %>
			<div class="field_error_messages">
			</div>
		<% end %>
	<% end %>
<% end %>

app/views/shared/_footer.html.erb
<div id="page-footer" class="">
	<div class="d-flex justify-content-center align-items-center">
	    <div class="align-items-center">
			<strong>Bulletin Business Listings</strong> - &copy; Copyright <%= Date.today.year %> - 
			<a href="https://www.bendbulletin.com">Central Oregon Media Group LLC</a>
		</div>
	</div>
	<div class="d-flex justify-content-around align-items-center">
		<div class="align-items-center">
			<i>

			</i>
		</div>
	</div>
	<br/>
	<br/>
</div>

app/views/shared/_header.html.erb
<div id="header_bar" class="bg-dark">
	<div class="container-fluid">
		<div class="row align-items-end">
			<div class="col d-flex align-items-end">
				<div id="branding" class="float-left">
					<h1>
						<%= link_to businesses_path do %>
							Bulletin <span>- Business Listings</span>
						<% end %>
					</h1>
				</div>
				<% if !current_user.nil? %>
					<div class="">
						<ul class="nav menu-items-bar">
							<% if current_user.admin_role? || current_user.supervisor_role? || current_user.sales_role? %>
								<li class="nav-item">
									<%= link_to "Businesses", businesses_path(:type=>'retail'), :class=>"nav-link menu-item-images" %>
								</li>
								<li class="nav-item">
									<%= link_to "Restaurants", businesses_path(:type=>'restaurant'), :class=>"nav-link menu-item-pages" %>
								</li>
							<% end %>
						</ul>
					</div>
				<% end %>
			</div>
			<div class="col-lg-1 col-md-1 col-sm-2 col-2">
				<div class="d-flex align-items-center">
					<%= render 'shared/nav_menu' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_messages.erb
<% if flash[:success] %>
	<div class="alert alert-success alert-dismissible fade show" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<%= flash[:success] %>
	</div>
<% end %>
<% if flash[:notice] %>
	<div class="alert alert-info alert-dismissible fade show" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<%= flash[:notice] %>
	</div>
<% end %>
<% if flash[:error] %>
	<div class="alert alert-warning alert-dismissible fade show" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<%= flash[:error] %>
	</div>
<% end %>
<% if flash[:admin_error] and admin? %>
	<div class="alert alert-warning alert-dismissible fade show" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<%= flash[:admin_error] %>
	</div>
<% end %>
<% flash.clear %>

app/views/shared/_nav_menu.html.erb
<div class="btn-group-vertical float-right">
	<div class="dropleft btn-block text-center menu-items-icon-admin">
		<button type="button" class="btn btn-secondary btn-menu" data-toggle="dropdown">
			<%= icon('bars fa-lg') %>
		</button>
		<div class="dropdown-menu">
			<% if current_user.nil? %>
				<%= link_to "Login", new_user_session_path, :class=>"dropdown-item" %>
				<%= link_to 'Register New Business', new_user_registration_path, :class=>"dropdown-item" %>
			<% else %>
				<%= link_to current_user.email, edit_user_registration_path, :class=>"dropdown-item" %>
				<div class="dropdown-divider"></div>
				<% if (can? :manage, Business) %>
					<%= link_to "Business List", businesses_path(:type=>'retail'), :class=>"dropdown-item" %>
					<%= link_to "Restaurant List", businesses_path(:type=>'restaurant'), :class=>"dropdown-item" %>
				<% else %>
					<%= link_to "My Businesses", businesses_path(), :class=>"dropdown-item" %>
				<% end %>

				<% if (can? :manage, BusinessType) || (can? :manage, ServiceType) || (can? :manage, Zone) %>
					<div class="dropdown-divider"></div>
					<%= link_to "Business Types", business_types_path, :class=>"dropdown-item" if can? :manage, BusinessType %>
					<%= link_to "Service Types", service_types_path, :class=>"dropdown-item" if can? :manage, ServiceType %>
					<%= link_to "Business Zones", zones_path, :class=>"dropdown-item" if can? :manage, Zone %>
				<% end %>

				<% if (can? :manage, User) %>
					<div class="dropdown-divider"></div>
					<%= link_to "Users", users_path, :class=>"dropdown-item" %>
				<% end %>
				<% if (can? :manage, DefaultSetting) %>
					<div class="dropdown-divider"></div>
					<%= link_to "Default Settings", default_settings_path, :class=>"dropdown-item" %>
				<% end %>

				<div class="dropdown-divider"></div>
				<%= link_to "Logout", destroy_user_session_path, :class=>"dropdown-item" %>
			<% end %>
		</div>
	</div>
</div>