config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users, :only => [:index, :show, :destroy] do
    put 'set_role'
    put 'password_reset_instructions'
  end
  
  get 'home/index'
  get 'welcome', :controller => 'home', :action => :welcome
  get 'business/index'

  resources :default_settings, :only => [:index, :edit, :update]
  resources :default_settings_emails
  
  resources :businesses do
    resources :create, controller: 'businesses/create', :only => [:show, :create, :update]
    collection do
      get 'business_listing_map'
      get 'business_listing'
      get 'maps'
      get 'get_map_markers'
    end
    put 'approve_business'
    put 'pause_business'
  end
  match "/create_business_wizard" => "businesses#create_business_wizard", :via => [:get]

  resources :business_types do
    get 'business_subtype_options', :on => :collection
  end
  resources :business_subtypes, :only => [:new, :create, :edit, :update, :destroy]
  resources :service_types
  resources :zones do
    get 'zone_region_options', :on => :collection
  end
  resources :regions
  resources :contacts, :only => [:new, :create, :edit, :update, :destroy]
  resources :awards, :only => [:new, :create, :edit, :update, :destroy]

  root 'home#index'
  #root 'businesses#index'
end

app/controllers/business_types_controller.rb
class BusinessTypesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  def index
    @business_types = BusinessType.all.order('name')
  end

  def show
    @business_type = BusinessType.find(params[:id])
  end

  def new
    @business_type = BusinessType.new
  end

  def create
    if params[:cancel_button]
      redirect_to business_types_path
    else
      @business_type = BusinessType.new(business_type_params)
      if @business_type.save
        flash[:notice] = "Business Type Created"
        redirect_to business_types_path
      else
        flash[:error] = "Business Type Creation Failed"
        render :action => :new
      end
    end    
  end

  def edit
    @business_type = BusinessType.find(params[:id])
  end

  def update
    @business_type = BusinessType.find(params[:id])
    if @business_type.update_attributes(business_type_params)
        flash[:notice] = "Business Type Updated"
        redirect_to business_types_path
    else
        flash[:error] = "Business Type Update Failed"
        render :action => :edit
    end
  end

  def destroy
    @business_type = BusinessType.find(params[:id])
    if @business_type.destroy
        flash[:notice] = "Business Type Killed"
        redirect_to business_types_path
    else
        flash[:error] = "Business Type Deletion Failed"
        redirect_to business_types_path
    end
  end

  def get_subtypes_for_business_type(business_type_id)
    #puts business_type_id.to_s
    @business_subtypes = BusinessType.find(business_type_id).business_subtypes unless business_type_id.nil?
    #puts @business_subtypes.inspect
  end

  def business_subtype_options
    business_subtypes = BusinessSubtype.where(:business_type_id => params[:business_type_id]) unless params[:business_type_id].nil?

    respond_to do |format|
      format.html
      format.json  { render :json => {:business_subtypes => business_subtypes} }
    end
  end

  private
    def business_type_params
      params.require(:business_type).permit(:name,:title_for_subtypes)
    end
end

app/helpers/business_types_helper.rb
module BusinessTypesHelper
end

app/views/business_types/edit.html.erb
<div class="business_type_heading">
	<h1><%= @business_type.name %></h1>
</div>

<div class="business_type_block" >
	<%= form_for(@business_type) do |f| %>
		<div class="form-group row">
			<label for="name" class="offset-1 col-3 col-form-label">Business Type:</label>
			<%= render 'shared/field_error_messages', object: @business_type, field: :name %>
			<div class="col-3">
				<%= f.text_field :name, class: "form-control", :placeholder => 'Retail, Restaurants,...' %>
			</div>
		</div>
		<div class="form-group row">
			<label for="name" class="offset-1 col-3 col-form-label">Title for SubTypes:</label>
			<%= render 'shared/field_error_messages', object: @business_type, field: :title_for_subtypes %>
			<div class="col-3">
				<%= f.text_field :title_for_subtypes, class: "form-control", :placeholder => 'Cuisine, Business Types,...' %>
			</div>
		</div>

		<div class="form-group row d-flex justify-content-end">
			<%= f.submit "Update", :class => 'btn btn-primary'%>
			<%= f.submit "Cancel", :name => 'cancel_button', :class => 'btn btn-primary'%>
		</div>
	<% end %>
</div>

app/views/business_types/index.html.erb
<div class="page-content">
	<div class="business_type_heading">
		<div class="d-flex justify-content-between align-items-center">
			<h2>Business Types</h2>
			<div class="float-right"><%= link_to "New Business Type", new_business_type_path %></div>
		</div>
	</div>

	<div class="business_type_block">
		<div class="">
			<% if @business_types %>
				<% unless @business_types.nil? %>
					<table id="businesss_types" class="table table-hover table-sm">
						<thead class="">
							<tr>
								<th class="">Type</th>
								<th class="">Subtypes</th>
								<th class="text-center">Action</th>
							</tr>
						</thead>
						<tbody>
							<% @business_types.each do |business_type| %>
								<tr class="table-info">
									<td class="align-middle"><%= business_type.name %></td>	
									<td class="align-middle">
										<small><%= link_to "Add #{business_type.name} #{business_type.title_for_subtypes.singularize}",
											new_business_subtype_path(:current_business_type=>business_type), :class => "" %></small>
									</td>
									<td class="text-center align-middle">
										<div class="btn">
											<%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_business_type_path(business_type),
												title: 'Edit', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
											<%= link_to icon('trash-o fa-lg'), 
												business_type_path(business_type),
												:method=> :delete, :action => 'destroy',
												data: {
													title: 'Delete '+business_type.name+'?', 
													confirm:'Delete this business type from the system?'},
												title: 'Delete', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
										</div>
									</td>
								</tr>
								<% business_type.business_subtypes.order("name").each do |subtype| %>
									<tr>
										<td></td>
										<td class="align-middle">
											<%= subtype.name %>
										</td>	
										<td class="text-center">
											<div class="btn">
												<%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_business_subtype_path(subtype),
													title: 'Edit', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
												<%= link_to icon('trash-o fa-lg'), 
													business_subtype_path(subtype),
													:method=> :delete, :action => 'destroy',
													data: {
														title: 'Delete '+subtype.name+'?', 
														confirm:'Delete this business subtype from the system?'},
													title: 'Delete', 'data-toggle' => 'tooltip', 'data-placement' => 'right' %>
											</div>
										</td>
									</tr>
								<% end %>
							<% end %>
						</tbody>
					</table>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/business_types/new.html.erb
<div class="business_type_heading">
	<div class="container search_container">
		<div class="row justify-content-between">
			<h1>New Business Type</h1>
		</div>
	</div>
</div>


<div class="business_type_block" >
	<%= form_for(@business_type) do |f| %>
		<div class="form-group row">
			<label for="name" class="offset-1 col-3 col-form-label">Business Type:</label>
			<%= render 'shared/field_error_messages', object: @business_type, field: :name %>
			<div class="col-3">
				<%= f.text_field :name, class: "form-control", :placeholder => 'Retail, Restaurants,...' %>
			</div>
		</div>
		<div class="form-group row">
			<label for="name" class="offset-1 col-3 col-form-label">Title for SubTypes:</label>
			<%= render 'shared/field_error_messages', object: @business_type, field: :title_for_subtypes %>
			<div class="col-3">
				<%= f.text_field :title_for_subtypes, class: "form-control", :placeholder => 'Cuisine, Business Types,...' %>
			</div>
		</div>

		<div class="form-group row d-flex justify-content-end">
			<%= f.submit "Update", :class => 'btn btn-primary'%>
			<%= f.submit "Cancel", :name => 'cancel_button', :class => 'btn btn-primary'%>
		</div>
	<% end %>
</div>